name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Set version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${VERSION}
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release /p:Version=${VERSION} --output ./nupkg
      
    - name: Push to NuGet
      run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: ./nupkg/*.nupkg 